name: Deploy Docs

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install mkdocs-material mkdocstrings[python] mkdocs-autorefs mkdocs-material[imaging]
          pip install -e ".[console,docker]"

      - name: Build Site (Local & CI)
        run: mkdocs build

      - name: Deploy to GitHub Pages (CI Only)
        # This prevents the Git push failure when running in act
        if: github.actor != 'nektos/act'
        run: mkdocs gh-deploy --force
